name: Vite-Electron Project Setup
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Install Yarn
      uses: npm install -D yarn
      with:
        registry-url: https://registry.npmjs.org/
 
    - name: Install dependencies
      run: yarn
 
    - name: Build project
      run: yarn build
 
    - name: Test project
      run: yarn test
